# Generated by Django 4.2.3 on 2023-11-02 15:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('contact_no', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('money', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('isadmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField()),
                ('time1', models.TimeField()),
                ('order_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('quantities', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('w', 'Ordered, on the way'), ('d', 'Order Delivered'), ('c', 'Order Cancelled')], max_length=20)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='sweets.user', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cw', models.CharField(choices=[('c', 'Cart'), ('w', 'Wishlist')], max_length=10)),
                ('p_id', models.ForeignKey(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, to='sweets.product')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to='sweets.user', to_field='username')),
            ],
        ),
    ]
