# Generated by Django 4.2.3 on 2023-12-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userreview', models.TextField()),
                ('sentment', models.CharField(choices=[('p', 'Positive'), ('n', 'Neutral'), ('b', 'Negative')], max_length=10)),
            ],
        ),
    ]
