# Generated by Django 4.2.3 on 2023-12-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='state',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
